module.exports = {
    apps: [
      {
        name: "3001.bison-casino",
        script: "npm",
        args: "run start",
        cwd: "/cms/onesite_app",
        env: {
          NODE_ENV: "production",
          PORT: 3001,
          ...require("dotenv").config({ path: ".env.3001.bison-casino" }).parsed,
        },
      },
      {
        name: "3002.fatpiratecasino",
        script: "npm",
        args: "run start",
        cwd: "/cms/onesite_app",
        env: {
          NODE_ENV: "production",
          PORT: 3002,
          ...require("dotenv").config({ path: ".env.3002.fatpiratecasino" }).parsed,
        },
      },
      {
        name: "3003.1onecasino",
        script: "npm",
        args: "run start",
        cwd: "/cms/onesite_app",
        env: {
          NODE_ENV: "production",
          PORT: 3003,
          ...require("dotenv").config({ path: ".env.3003.1onecasino" }).parsed,
        },
      },
      {
        name: "3004.brunocasino2",
        script: "npm",
        args: "run start",
        cwd: "/cms/onesite_app",
        env: {
          NODE_ENV: "production",
          PORT: 3004,
          ...require("dotenv").config({ path: ".env.3004.brunocasino2" }).parsed,
        },
      },
      {
        name: "3005.unique-casino1",
        script: "npm",
        args: "run start",
        cwd: "/cms/onesite_app",
        env: {
          NODE_ENV: "production",
          PORT: 3005,
          ...require("dotenv").config({ path: ".env.3005.unique-casino1" }).parsed,
        },
      },
      {
        name: "3006.amon-casino1",
        script: "npm",
        args: "run start",
        cwd: "/cms/onesite_app",
        env: {
          NODE_ENV: "production",
          PORT: 3006,
          ...require("dotenv").config({ path: ".env.3006.amon-casino1" }).parsed,
        },
      },
      {
        name: "3007.betonred2",
        script: "npm",
        args: "run start",
        cwd: "/cms/onesite_app",
        env: {
          NODE_ENV: "production",
          PORT: 3007,
          ...require("dotenv").config({ path: ".env.3007.betonred2" }).parsed,
        },
      },
      {
        name: "3008.hitnspin.de.com",
        script: "npm",
        args: "run start",
        cwd: "/cms/onesite_app",
        env: {
          NODE_ENV: "production",
          PORT: 3008,
          ...require("dotenv").config({ path: ".env.3008.hitnspin.de.com" }).parsed,
        },
      },
      {
        name: "3009.jokabet.org.uk",
        script: "npm",
        args: "run start",
        cwd: "/cms/onesite_app",
        env: {
          NODE_ENV: "production",
          PORT: 3009,
          ...require("dotenv").config({ path: ".env.3009.jokabet.org.uk" }).parsed,
        },
      },
      {
        name: "3010.goldenbet.org.uk",
        script: "npm",
        args: "run start",
        cwd: "/cms/onesite_app",
        env: {
          NODE_ENV: "production",
          PORT: 3010,
          ...require("dotenv").config({ path: ".env.3010.goldenbet.org.uk" }).parsed,
        },
      },
      {
        name: "3011.9ninecasino.es",
        script: "npm",
        args: "run start",
        cwd: "/cms/onesite_app",
        env: {
          NODE_ENV: "production",
          PORT: 3011,
          ...require("dotenv").config({ path: ".env.3011.9ninecasino.es" }).parsed,
        },
      },
      {
        name: "3012.casinomidas.org.es",
        script: "npm",
        args: "run start",
        cwd: "/cms/onesite_app",
        env: {
          NODE_ENV: "production",
          PORT: 3012,
          ...require("dotenv").config({ path: ".env.3012.casinomidas.org.es" }).parsed,
        },
      },
      {
        name: "3013.xkon.gr",
        script: "npm",
        args: "run start",
        cwd: "/cms/onesite_app",
        env: {
          NODE_ENV: "production",
          PORT: 3013,
          ...require("dotenv").config({ path: ".env.3013.xkon.gr" }).parsed,
        },
      },
      {
        name: "3014.linked-statistics.gr",
        script: "npm",
        args: "run start",
        cwd: "/cms/onesite_app",
        env: {
          NODE_ENV: "production",
          PORT: 3014,
          ...require("dotenv").config({ path: ".env.3014.linked-statistics.gr" }).parsed,
        },
      },
      {
        name: "3015.pallini-beach.gr",
        script: "npm",
        args: "run start",
        cwd: "/cms/onesite_app",
        env: {
          NODE_ENV: "production",
          PORT: 3015,
          ...require("dotenv").config({ path: ".env.3015.pallini-beach.gr" }).parsed,
        },
      },
      {
        name: "3016.greekta.gr",
        script: "npm",
        args: "run start",
        cwd: "/cms/onesite_app",
        env: {
          NODE_ENV: "production",
          PORT: 3016,
          ...require("dotenv").config({ path: ".env.3016.greekta.gr" }).parsed,
        },
      },
      {
        name: "3017.veriafc.gr",
        script: "npm",
        args: "run start",
        cwd: "/cms/onesite_app",
        env: {
          NODE_ENV: "production",
          PORT: 3017,
          ...require("dotenv").config({ path: ".env.3017.veriafc.gr" }).parsed,
        },
      },
      {
        name: "3018.snapkey.fr",
        script: "npm",
        args: "run start",
        cwd: "/cms/onesite_app",
        env: {
          NODE_ENV: "production",
          PORT: 3018,
          ...require("dotenv").config({ path: ".env.3018.snapkey.fr" }).parsed,
        },
      },
      {
        name: "3019.reves-doceans.fr",
        script: "npm",
        args: "run start",
        cwd: "/cms/onesite_app",
        env: {
          NODE_ENV: "production",
          PORT: 3019,
          ...require("dotenv").config({ path: ".env.3019.reves-doceans.fr" }).parsed,
        },
      },
      {
        name: "3020.museehistoiredufer.fr",
        script: "npm",
        args: "run start",
        cwd: "/cms/onesite_app",
        env: {
          NODE_ENV: "production",
          PORT: 3020,
          ...require("dotenv").config({ path: ".env.3020.museehistoiredufer.fr" }).parsed,
        },
      },
      {
        name: "3021.associazioneitaliarussia.it",
        script: "npm",
        args: "run start",
        cwd: "/cms/onesite_app",
        env: {
          NODE_ENV: "production",
          PORT: 3021,
          ...require("dotenv").config({ path: ".env.3021.associazioneitaliarussia.it" }).parsed,
        },
      },
      {
        name: "3022.rucst.co.uk",
        script: "npm",
        args: "run start",
        cwd: "/cms/onesite_app",
        env: {
          NODE_ENV: "production",
          PORT: 3022,
          ...require("dotenv").config({ path: ".env.3022.rucst.co.uk" }).parsed,
        },
      },
      {
        name: "3023.coachfederation.it",
        script: "npm",
        args: "run start",
        cwd: "/cms/onesite_app",
        env: {
          NODE_ENV: "production",
          PORT: 3023,
          ...require("dotenv").config({ path: ".env.3023.coachfederation.it" }).parsed,
        },
      },
      {
        name: "3024.formazioneprofessionalelombardia.it",
        script: "npm",
        args: "run start",
        cwd: "/cms/onesite_app",
        env: {
          NODE_ENV: "production",
          PORT: 3024,
          ...require("dotenv").config({ path: ".env.3024.formazioneprofessionalelombardia.it" }).parsed,
        },
      },
      {
        name: "3025.genderpanteion.gr",
        script: "npm",
        args: "run start",
        cwd: "/cms/onesite_app",
        env: {
          NODE_ENV: "production",
          PORT: 3025,
          ...require("dotenv").config({ path: ".env.3025.genderpanteion.gr" }).parsed,
        },
      },
      {
        name: "3026.ependisinews.gr",
        script: "npm",
        args: "run start",
        cwd: "/cms/onesite_app",
        env: {
          NODE_ENV: "production",
          PORT: 3026,
          ...require("dotenv").config({ path: ".env.3026.ependisinews.gr" }).parsed,
        },
      },
      {
        name: "3027.huaweistore.gr",
        script: "npm",
        args: "run start",
        cwd: "/cms/onesite_app",
        env: {
          NODE_ENV: "production",
          PORT: 3027,
          ...require("dotenv").config({ path: ".env.3027.huaweistore.gr" }).parsed,
        },
      },
      {
        name: "3028.ies.org.ro",
        script: "npm",
        args: "run start",
        cwd: "/cms/onesite_app",
        env: {
          NODE_ENV: "production",
          PORT: 3028,
          ...require("dotenv").config({ path: ".env.3028" }).parsed,
        },
      },
      {
        name: "3029.unesco-hellas.gr",
        script: "npm",
        args: "run start",
        cwd: "/cms/onesite_app",
        env: {
          NODE_ENV: "production",
          PORT: 3029,
          ...require("dotenv").config({ path: ".env.3029" }).parsed,
        },
      },
      {
        name: "3030.plinko-soldi-veri.co.it",
        script: "npm",
        args: "run start",
        cwd: "/cms/onesite_app",
        env: {
          NODE_ENV: "production",
          PORT: 3030,
          ...require("dotenv").config({ path: ".env.3030" }).parsed,
        },
      },
      {
        name: "3031.dogana-project.eu",
        script: "npm",
        args: "run start",
        cwd: "/cms/onesite_app",
        env: {
          NODE_ENV: "production",
          PORT: 3031,
          ...require("dotenv").config({ path: ".env.3031" }).parsed,
        },
      },
      {
        name: "3032.geo-in.eu",
        script: "npm",
        args: "run start",
        cwd: "/cms/onesite_app",
        env: {
          NODE_ENV: "production",
          PORT: 3032,
          ...require("dotenv").config({ path: ".env.3032" }).parsed,
        },
      },
      {
        name: "3033.200m.pt",
        script: "npm",
        args: "run start",
        cwd: "/cms/onesite_app",
        env: {
          NODE_ENV: "production",
          PORT: 3033,
          ...require("dotenv").config({ path: ".env.3033" }).parsed,
        },
      },
      {
        name: "3034.agrocluster.pt",
        script: "npm",
        args: "run start",
        cwd: "/cms/onesite_app",
        env: {
          NODE_ENV: "production",
          PORT: 3034,
          ...require("dotenv").config({ path: ".env.3034" }).parsed,
        },
      },
      {
        name: "3035.artwalk.org.uk",
        script: "npm",
        args: "run start",
        cwd: "/cms/onesite_app",
        env: {
          NODE_ENV: "production",
          PORT: 3035,
          ...require("dotenv").config({ path: ".env.3035" }).parsed,
        },
      },
      {
        name: "3036.gisap.eu",
        script: "npm",
        args: "run start",
        cwd: "/cms/onesite_app",
        env: {
          NODE_ENV: "production",
          PORT: 3036,
          ...require("dotenv").config({ path: ".env.3036" }).parsed,
        },
      },
      {
        name: "3037.plinko-argent-reel.fr",
        script: "npm",
        args: "run start",
        cwd: "/cms/onesite_app",
        env: {
          NODE_ENV: "production",
          PORT: 3037,
          ...require("dotenv").config({ path: ".env.3037" }).parsed,
        },
      },
    ],
};